NUMPY ASSIGNMENT

'''1. What is a Python library? Why do we use Python libraries?'''



Python library is simply a collection of codes or modules of codes that we can use in a program for specific operations
Python libraries are collections of reusable code modules that you can integrate into your projects to save time and effort.

In [ ]:
#Q2. What is the difference between Numpy array and List?
Numpy Array is very faster than List because it is based on C++ programming and 

In [1]:
import numpy as np

In [4]:
#Q3.Find the shape, size and dimension of the following array?
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

print("Dimension of the array a is", a.ndim)
print("Shape of the array a is", a.shape)
print("Size of the array a is", a.size)

Dimension of the array a is 2
Shape of the array a is (3, 4)
Size of the array a is 12


In [10]:
#Q4. Write python code to access the first row of the following array?
b = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
b[0]

array([1, 2, 3, 4])

In [4]:
#Q5. How do you access the element at the third row and fourth column from the given numpy array?

c= np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
c[2,3]

12

In [ ]:
#Q6. Write code to extract all odd-indexed elements from the given numpy array?
d= np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
 

In [12]:
#7. How can you generate a random 3x3 matrix with values between 0 and 1?
arr = np.random.randint(0,2,(3,3))
arr

array([[0, 1, 1],
       [0, 1, 1],
       [0, 0, 1]])

#8.Describe the difference between np.random.rand and np.random.randn?

np.random.rand() - Provides Random Values of a given shape using uniform distribution

np.random.randn() - Takes input of non negative values and Provides Random Values of a given shape using normal distribution distribution 

In [37]:
#9. Write code to increase the dimension of the following array?
e= np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

print('Present dimension of the given array is 2D', e)

f = np.array([[[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]]])

print('Now the dimension has been changed to 3d', f)

Present dimension of the given array is 2D [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Now the dimension has been changed to 3d [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [40]:
#10. How to transpose the following array in NumPy?
f = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
g = f.transpose()
g #transpose of the following array

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [14]:
#11. Consider the following matrix:
A = [1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]
B = [1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]

In [17]:
Matrix_A2 = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

In [20]:
Matrix_B2 = np.array(B)
Matrix_B2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
#1. Index wise multiplication
Index_wise_multiplication = Matrix_A2*Matrix_B2
Index_wise_multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [29]:
#2. Matix multiplication
Matrix_multiplication = np.multiply(Matrix_A2,Matrix_B2)
Matrix_multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [30]:
#3.Add both the matrix
Matrix_add = np.add(Matrix_A2,Matrix_B2)
Matrix_add

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [33]:
#4. Subtract matrix B from A
Matrix_sub = np.subtract(Matrix_B2,Matrix_A2)
Matrix_sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
#5.Divide Matix B by A
Matrix_div = np.divide(Matrix_B2,Matrix_A2)
Matrix_div

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#12. Which function in Numpy can be used to swap the byte order of an array?

np.ndarray.byteswap()

13. What is the significance of the np.linalg.inv function?

np.linalg.inv --> We use numpy.linalg.inv() function to calculate the inverse of a matrix

In [45]:
arr2 = np.array([[ 1,  2,  3], [ 5,  6,  7],[ 9, 10, 11]])

In [46]:
np.linalg.inv(arr2)

array([[ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14],
       [-1.12589991e+15,  2.25179981e+15, -1.12589991e+15],
       [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14]])

14. What does the np.reshape function do, and how is it used?

np.reshape is used to change the shape of the array without changing its data

In [49]:
arr3 = np.array([[ 1,  2], [ 5,  6],[ 9, 10]])

In [57]:
np.reshape(arr3, (3,2))

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

15. What is broadcasting in Numpy?

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.